use_frameworks!

platform :ios, '10.0'

pre_install do |installer|

def installer.verify_no_static_framework_transitive_dependencies; end

end

post_install do |installer|

       installer.pods_project.targets.each do |target|

           target.build_configurations.each do |config|

             config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] ="13"

           end

         end

end


target 'SKNetMintorLib_Example' do
  pod 'SKNetMintorLib', :path => '../'
end
